[workspace]
authors = ["Daniel Hueholt"]
channels = ["conda-forge"]
name = "gdd"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.7.*"
cmasher = ">=1.9.2,<2"
icecream = ">=2.1.8,<3"
matplotlib = ">=3.10.6,<4"
numpy = ">=2.3.3,<3"
xarray = ">=2025.9.1,<2026"
rioxarray = ">=0.19.0,<0.20"
scipy = ">=1.16.2,<2"
cftime = ">=1.6.4,<2"
geopandas = ">=1.1.1,<2"
xesmf = ">=0.8.10,<0.9"
opencv = ">=4.12.0,<5"
cmocean = ">=4.0.3,<5"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.7.2,<2"
cartopy = ">=0.25.0,<0.26"
ipykernel = ">=6.30.1,<7"
pip = ">=25.2,<26"
dask = ">=2025.9.1,<2026"
netcdf4 = ">=1.7.2,<2"
bottleneck = ">=1.6.0,<2"
polars = ">=1.34.0,<2"
